### ISSUE TITLE
GUI showing multiple duplicate receive TX with different timestamps

### ISSUE THREAD

**Issue by BigslimVdub** [aeonix/aeon-gui#39] opened 2020-01-24 05:56 UTC
OSX 
v0.13.1.0

<img width="612" alt="Duplicate TX" src="https://user-images.githubusercontent.com/30030687/73047404-47fd5a00-3e3b-11ea-8339-54a49f55afff.png">

There are many of these showing up. They show "unconfirmed" in block height. IT is only for TX received.

**Comment by stoffu** [comment] 2020-02-17 08:46
I cannot reproduce this issue. Can you explain how to reproduce it?

**Comment by stoffu** [comment] 2020-02-17 12:31
It's a bug in the CLI repo fixed in https://github.com/aeonix/aeon/pull/169

**Closed** 2020-02-18 20:52 UTC
